### ISSUE TITLE
Please update fix DSM 7.1 

### ISSUE THREAD

**Issue by dnmnhat** [Little-Karl/catdrive-fix#4]
I accidentally updated to DSM 7.1 RC, 
hope you update fix for DSM 7.1.
Thanks !

**Comment by Little-Karl** [comment]
well, I don't have a catdrive anymore. I moved to using redpill for a bit and went all the way back to back to barebone ubuntu server. I'm thinking of getting one to give it to my friend so I can have a small but safe offsite backup that is close to me.

But as far as I know, there isn't a 7.1 uboot firmware for it, every time I want to roll back I just flash the 6.something firmware and install the 7.0 image. I'm not the one who makes the firmware nor do I know how to make one. The bin in the repo came from the seller who sold the thing to me

**Comment by Little-Karl** [comment]
Anyway, I've uploaded a firmware bin file(mtdfull.bin) to the repo alone with a png of the command needed to flash it. Doing it wrong can brick the hardware and you'll need to use a uart console or something, it's a huge mess, thank god I have never bricked it and don't have to figure that out. Also, it's kina of old, and I don't even have the hardware to test it anymore so, do it at your own risk, and good luck

PS: I am not responsible for any damaged hardware

**Comment by dnmnhat** [comment]
I will look into this.
Thank you for sharing how to fix DSM 7.0 and more.
